repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
        - id: check-added-large-files
    - repo: local
      hooks:
        - id: black
          name: black
          entry: poetry run black .
          language: system
          always_run: true
          pass_filenames: false
        - id: isort
          name: isort
          entry: poetry run isort .
          language: system
          always_run: true
          pass_filenames: false
        - id: mypy
          name: mypy
          entry: poetry run mypy .
          language: system
          always_run: true
          pass_filenames: false
        - id: flake8
          name: flake8
          entry: poetry run flake8 .
          language: system
          always_run: true
          pass_filenames: false
        - id: pydocstyle
          name: pydocstyle
          entry: poetry run pydocstyle .
          language: system
          always_run: true
          pass_filenames: false
        - id: pytest
          name: pytest
          entry: poetry run pytest tests
          language: system
          always_run: true
          pass_filenames: false
        - id: gerar requirements
          name: gerar requirements
          entry: sh requirements.sh
          language: system
          always_run: true
          pass_filenames: false