site_name: Timeless
site_url: https://ericmiguel.github.io/timeless
site_description: Timeless - a datetime toolkit for people in a hurry
copyright: Copyright &copy; 2022 Eric Miguel

theme:
  name: material
  palette: 
    - scheme: default
      primary: deep orange
      accent: amber
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate 

repo_name: ericmiguel/timeless
repo_url: https://github.com/ericmiguel/timeless

extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/ericmrib
    - icon: fontawesome/brands/github
      link: https://github.com/ericmiguel

nav:
- Introduction: index.md
- Datetime:
  - Basics: datetime/basic.md
  - Datetime operations: datetime/operations.md
  - Datetime parsing: datetime/parsing.md
  - Datetime conveniences: datetime/conveniences.md
  - Reference: datetime/reference.md
- Period:
  - Basics: period/basic.md
  - Reference: period/reference.md
- Converters:
  - Basics: converters/basic.md
  - Default datetime: converters/default_datetime.md
  - Pandas: converters/pandas.md
  - Numpy: converters/numpy.md
  - Reference: converters/reference.md
- Helpers:
  - Basics: helpers/basic.md
  - Reference: helpers/reference.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          heading_level: 2
          show_root_full_path: true
          show_root_members_full_path: true
          show_category_heading: true
          docstring_style: "numpy"
          merge_init_into_class: true
          docstring_section_style: list
          show_signature_annotations: true
          show_submodules: true