site_name: Timeless
site_url: https://ericmiguel.github.io/timeless
site_description: Timeless - a datetime toolkit for people in a hurry
copyright: Copyright &copy; 2022 Eric Miguel

theme:
  name: material
  palette: 
    - scheme: default
      primary: deep orange
      accent: amber
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate 

repo_name: ericmiguel/timeless
repo_url: https://github.com/ericmiguel/timeless

extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/ericmrib
    - icon: fontawesome/brands/github
      link: https://github.com/ericmiguel

nav:
- Timeless: index.md
- Datetime:
  - Datetime basics: datetime/basic.md
  - Datetime conveniences: datetime/conveniences.md
- Period:
  - Period basics: period/basic.md
- Converters:
  - Default datetime and Timeless: converters/default_datetime.md
  - Pandas and Timeless: converters/pandas.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
